spring:
  application:
    name: flash-deal-app
  
  datasource:
    url: jdbc:postgresql://postgres:5432/flashdeal_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: 8080

logging:
  level:
    com.flashdeal: DEBUG
    org.springframework.web: INFO
